FROM harbor.salceson.pl/external/dockerhub/opensearch:2.5.0
RUN /usr/share/opensearch/bin/opensearch-plugin install analysis-icu
RUN /usr/share/opensearch/bin/opensearch-plugin install analysis-phonetic
